export const RELEASE_STATUSES = {
  DRAFT: "DRAFT",
  IN_PROGRESS: "IN_PROGRESS",
  READY_FOR_APPROVAL: "READY_FOR_APPROVAL",
  APPROVED: "APPROVED",
  SCHEDULED: "SCHEDULED",
  DEPLOYING: "DEPLOYING",
  DEPLOYED: "DEPLOYED",
  FAILED: "FAILED",
  ROLLED_BACK: "ROLLED_BACK",
} as const;

export type ReleaseStatus =
  (typeof RELEASE_STATUSES)[keyof typeof RELEASE_STATUSES];